### PR TITLE
Add me to the list of contributors

### PR DESCRIPTION
**Pull request by dlech**

### CODE REVIEW

**Comment by kortschak** [comment]
You are an AUTHOR too.

**Comment by dlech** [comment]
I had no idea.

**Comment by kortschak** [comment]
The only reason for separation of AUTHOR and CONTRIBUTOR is that some contributors in some projects are doing the work on their bosses time and may need to cede copyright ownership to their boss. The CONTRIBUTOR list is people who have written code, AUTHORS is the list of legal entities who hold copyright. At the moment they match completely in this project except for Renée because she hold copyright on the gopher, but I made the logo.

**Comment by kortschak** [comment]
Thank you.

**Pull request merged**
