### PR TITLE
Fix buttons since 18-ev3dev kernel

### PR DESCRIPTION
**Pull request by dlech**
trying this again since I don't know what happened in #35.

### CODE REVIEW

**Comment by kortschak** [comment]
It is probably worth noting in README.md that the required kernel is 18-ev3dev.

**Comment by dlech** [comment]
updated readme

**Comment by kortschak** [comment]
Thank you.

**Comment by kortschak** [comment]
Oh, sorry, I forgot to ask you to add yourself to C+A. Would you send a PR for that?

**Pull request merged**
